import React from 'react'

export default function Loomer() {
  return (
    <div className='h-fit w-screen bg-red-600'>
     <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Corporis sit accusamus ipsum error beatae, qui ex atque dolore sunt laborum excepturi libero inventore blanditiis quaerat natus tempora? Rerum expedita quae, ipsam excepturi quam facilis ad inventore explicabo tempore sapiente consequatur laboriosam nisi corporis perferendis minima deleniti magni ipsa quis alias reiciendis ea illum. Explicabo assumenda officiis dolorum quis dolor quod distinctio fugit sint accusamus nemo amet repellat tempore mollitia, voluptate, quo at voluptates beatae maiores saepe quasi natus? Quasi repudiandae voluptate quibusdam, ad alias ratione cum ipsam, itaque animi adipisci inventore? Harum alias maiores accusantium provident eius voluptate unde, deserunt culpa ut fugit nesciunt officia voluptas eum quae dicta veritatis? Qui sint autem amet dolorem id pariatur voluptate, consequuntur maxime ducimus et voluptatum, sunt laboriosam consequatur rerum repudiandae aperiam ea accusamus sapiente facilis, debitis ratione. Distinctio a maiores vero, amet inventore magnam rerum laborum? Eius reprehenderit ut modi quos tenetur magni fugit totam voluptates consequatur, est autem deleniti rem doloremque quia minus illum assumenda, dignissimos maiores nulla. Repudiandae facilis, architecto est voluptas soluta tempore sunt neque sapiente exercitationem asperiores maiores perferendis quo eum ullam porro natus dolor hic saepe rerum adipisci aperiam totam dolores quas dolorem. Nostrum in adipisci, eaque eum porro magni illum ipsam, reprehenderit praesentium assumenda quae neque itaque sequi vitae? Ratione incidunt accusantium dolores placeat vero aut dolorem dicta! Placeat numquam magni enim consequuntur veritatis libero a, voluptates doloremque neque non exercitationem, magnam ipsam! Veniam, ipsam, ipsa a facere sint omnis architecto impedit nostrum possimus aliquid natus numquam hic tenetur esse rerum repellendus in illum molestias obcaecati voluptates recusandae nulla quaerat temporibus iusto! Obcaecati molestias placeat distinctio odio, hic quisquam quos aperiam ad ipsum totam voluptate sint exercitationem ipsa deserunt nemo maxime explicabo, voluptates, tempore dicta omnis ex autem cumque? Alias expedita cum ullam soluta inventore qui!</p>      
    </div>
  )
}
